#!/bin/bash

# Prompt the user for a filename
read -p "Enter the TypeScript filename (without extension): " filename

# Ensure a filename is provided
if [[ -z "$filename" ]]; then
    echo "Error: No filename provided."
    exit 1
fi

# Define the file path
filepath="${filename}.ts"

# Write TypeScript content to the file
echo "Creating TypeScript file: $filepath"

cat <<EOL > "$filepath"
// TypeScript file generated by Bash script

export const greet = (name: string): string => {
    return \`Hello, \${name}!\`;
};

console.log(greet("World"));
EOL

# Confirm file creation
echo "File '$filepath' created successfully!"
